import fs from "fs";
import path from "path";
import { getStitchClient, StitchError } from "../lib/stitch-client.js";
import { readMetadata, writeMetadata, type StitchMetadata, type DesignTheme } from "../lib/metadata.js";

const DESIGN_MD_TEMPLATE = `# Design System: {title}

**Project ID:** {projectId}

## 1. Visual Theme & Atmosphere

{atmosphere}

## 2. Color Palette & Roles

| Color Name | Hex Code | Role |
|------------|----------|------|
{colors}
## 3. Typography Rules

- **Font Family:** {font}
- **Headline Font:** {headlineFont}
- **Body Font:** {bodyFont}
- **Label Font:** {labelFont}
- **Weights:** {weights}
- **Usage:** {usage}

## 4. Component Stylings

### Buttons
{buttons}

### Cards/Containers
{cards}

### Inputs/Forms
{inputs}

## 5. Layout Principles

{layout}

## 6. Design System Notes for Stitch Generation

When generating new screens, use these tokens:

- **Color Mode:** {colorMode}
- **Color Variant:** {colorVariant}
- **Primary Color:** {customColor}
- **Font:** {font}
- **Roundness:** {roundness}
- **Saturation:** {saturation}
- **Spacing Scale:** {spacingScale}

---

_Generated by stitch-mcp-cli on {date}_
`;

function describeRoundness(roundness: string): string {
  const descriptions: Record<string, string> = {
    ROUND_TWO: "Subtly rounded corners (2px)",
    ROUND_FOUR: "Gently rounded corners (4px)",
    ROUND_EIGHT: "Noticeably rounded corners (8px)",
    ROUND_TWELVE: "Prominently rounded corners (12px)",
    ROUND_FULL: "Pill-shaped (fully rounded)",
    ROUNDNESS_UNSPECIFIED: "Default roundness",
  };
  return descriptions[roundness] || roundness;
}

function describeColorMode(mode: string): string {
  const descriptions: Record<string, string> = {
    LIGHT: "Light mode with bright, airy feel",
    DARK: "Dark mode with deep, immersive feel",
    COLOR_MODE_UNSPECIFIED: "Default color mode",
  };
  return descriptions[mode] || mode;
}

function describeColorVariant(variant: string): string {
  const descriptions: Record<string, string> = {
    MONOCHROME: "Single hue variations",
    NEUTRAL: "Neutral, subdued palette",
    TONAL_SPOT: "Tonal variations of primary color",
    VIBRANT: "Bold, saturated colors",
    EXPRESSIVE: "Expressive, dynamic palette",
    FIDELITY: "True-to-source color fidelity",
    CONTENT: "Content-driven color extraction",
    RAINBOW: "Full spectrum rainbow palette",
    FRUIT_SALAD: "Playful, fruity color combinations",
  };
  return descriptions[variant] || variant || "Default";
}

function generateDesignMd(metadata: StitchMetadata): string {
  const theme = metadata.designTheme || {
    colorMode: "LIGHT",
    font: "INTER",
    roundness: "ROUND_EIGHT",
    customColor: "#4F46E5",
    saturation: 1,
  };

  const atmosphere = describeColorMode(theme.colorMode || "LIGHT");
  const roundnessDesc = describeRoundness(theme.roundness || "ROUND_EIGHT");
  const colorVariantDesc = describeColorVariant(theme.colorVariant || "");

  const colors = [
    { name: "Primary", hex: theme.overridePrimaryColor || theme.customColor || "#4F46E5", role: "Primary actions, key interactive elements" },
    { name: "Secondary", hex: theme.overrideSecondaryColor || "#10B981", role: "Secondary actions, success states" },
    { name: "Tertiary", hex: theme.overrideTertiaryColor || "#F59E0B", role: "Tertiary actions, warnings" },
    { name: "Neutral", hex: theme.overrideNeutralColor || "#6B7280", role: "Neutral elements, disabled states" },
    { name: "Background", hex: theme.backgroundLight || (theme.colorMode === "DARK" ? "#1F2937" : "#FFFFFF"), role: "Page background" },
    { name: "Background Dark", hex: theme.backgroundDark || (theme.colorMode === "DARK" ? "#111827" : "#F3F4F6"), role: "Dark variant background" },
    { name: "Surface", hex: theme.colorMode === "DARK" ? "#374151" : "#F3F4F6", role: "Card backgrounds, elevated surfaces" },
    { name: "Text Primary", hex: theme.colorMode === "DARK" ? "#F9FAFB" : "#111827", role: "Main text content" },
    { name: "Text Secondary", hex: theme.colorMode === "DARK" ? "#9CA3AF" : "#6B7280", role: "Secondary text, labels" },
  ];

  if (theme.namedColors) {
    for (const [name, hex] of Object.entries(theme.namedColors)) {
      colors.push({ name, hex, role: `Custom color: ${name}` });
    }
  }

  const colorsTable = colors
    .map((c) => `| ${c.name} | ${c.hex} | ${c.role} |`)
    .join("\n");

  return DESIGN_MD_TEMPLATE
    .replace("{title}", metadata.title || "Untitled Project")
    .replace("{projectId}", metadata.projectId)
    .replace("{atmosphere}", atmosphere)
    .replace("{colors}", colorsTable)
    .replace("{font}", theme.font || "INTER")
    .replace("{headlineFont}", theme.headlineFont || theme.font || "INTER")
    .replace("{bodyFont}", theme.bodyFont || theme.font || "INTER")
    .replace("{labelFont}", theme.labelFont || theme.font || "INTER")
    .replace("{weights}", "Regular (400), Medium (500), Bold (700)")
    .replace("{usage}", "Use bold for headings, regular for body text, medium for UI labels")
    .replace("{buttons}", `Shape: ${roundnessDesc}\nColors: Primary color with hover states`)
    .replace("{cards}", `Corner radius: ${roundnessDesc}\nBackground: Surface color with subtle shadow`)
    .replace("{inputs}", `Border radius: ${roundnessDesc}\nBackground: Slightly darker than page`)
    .replace("{layout}", `16px base spacing grid, 8px for tight spacing, 24px for sections${theme.spacingScale ? `\nSpacing scale: ${theme.spacingScale}` : ""}`)
    .replace("{colorMode}", theme.colorMode || "LIGHT")
    .replace("{colorVariant}", colorVariantDesc)
    .replace("{customColor}", theme.overridePrimaryColor || theme.customColor || "#4F46E5")
    .replace("{font}", theme.font || "INTER")
    .replace("{roundness}", roundnessDesc)
    .replace("{saturation}", String(theme.saturation || 1))
    .replace("{spacingScale}", String(theme.spacingScale || 1))
    .replace("{date}", new Date().toISOString().split("T")[0]);
}

export async function designMd(options: { projectId?: string; output?: string; sync?: boolean }) {
  const outputPath = options.output || "DESIGN.md";

  try {
    const { stitch, callTool } = getStitchClient();

    let projectId = options.projectId;
    let project;

    if (projectId) {
      project = stitch.project(projectId);
    } else {
      const metadata = readMetadata();
      if (metadata?.projectId) {
        projectId = metadata.projectId;
        project = stitch.project(projectId);
      } else {
        const projects = await stitch.projects();
        if (projects.length === 0) {
          console.error("No projects found. Provide a project ID or create one first.");
          process.exit(1);
        }
        project = projects[0];
        projectId = project.id;
      }
    }

    console.log(`Fetching project details for: ${projectId}`);

    const projectDetails = await callTool("get_project", { name: `projects/${projectId}` }) as any;

    const metadata: StitchMetadata = {
      projectId: projectId!,
      title: projectDetails?.title || "Untitled",
      deviceType: projectDetails?.deviceType || "MOBILE",
      designTheme: projectDetails?.designTheme as DesignTheme || undefined,
      screens: {},
    };

    try {
      console.log("Fetching design systems...");
      const designSystems = await project.listDesignSystems();
      if (designSystems.length > 0) {
        const ds = designSystems[0];
        console.log(`Using design system: ${(ds as any).assetId || (ds as any).id}`);
        if (ds.data?.theme) {
          metadata.designTheme = {
            ...metadata.designTheme,
            ...ds.data.theme,
          };
        }
        if (ds.data?.displayName) {
          console.log(`Design system name: ${ds.data.displayName}`);
        }
      }
    } catch (dsError) {
      console.log(`Note: Could not fetch design systems: ${dsError instanceof Error ? dsError.message : String(dsError)}`);
    }

    const screens = await project.screens();
    console.log(`Project has ${screens.length} screens`);

    if (!fs.existsSync(".stitch")) {
      fs.mkdirSync(".stitch", { recursive: true });
    }

    writeMetadata(metadata);

    const designMdContent = generateDesignMd(metadata);
    fs.writeFileSync(outputPath, designMdContent);

    console.log(`OK Design system saved to ${outputPath}`);
    console.log(`OK Metadata saved to .stitch/metadata.json`);

    if (options.sync) {
      console.log("\nSyncing all screens to .stitch/designs/...");
      const designsDir = path.join(".stitch", "designs");
      if (!fs.existsSync(designsDir)) {
        fs.mkdirSync(designsDir, { recursive: true });
      }

      for (const screen of screens) {
        try {
          const html = await screen.getHtml();
          const screenFile = path.join(designsDir, `${screen.screenId.slice(0, 8)}.html`);
          fs.writeFileSync(screenFile, html);
          console.log(`  OK ${screen.screenId.slice(0, 8)}`);
        } catch (error) {
          console.error(`  X ${screen.screenId}: ${error instanceof Error ? error.message : error}`);
        }
      }
      console.log(`\nOK ${screens.length} screens synced to ${designsDir}`);
    }
  } catch (error) {
    if (error instanceof StitchError) {
      console.error(`Error [${error.code}]: ${error.message}`);
      if (error.suggestion) console.error(`Sugerencia: ${error.suggestion}`);
    } else {
      console.error("Error generating design system:", error instanceof Error ? error.message : error);
    }
    process.exit(1);
  }
}
