import fs from "fs";
import path from "path";
import { getStitchClient } from "../lib/stitch-client.js";
import { readMetadata, writeMetadata, type StitchMetadata, type DesignTheme } from "../lib/metadata.js";

const DESIGN_MD_TEMPLATE = `# Design System: {title}

**Project ID:** {projectId}

## 1. Visual Theme & Atmosphere

{atmosphere}

## 2. Color Palette & Roles

| Color Name | Hex Code | Role |
|------------|----------|------|
{colors}
## 3. Typography Rules

- **Font Family:** {font}
- **Weights:** {weights}
- **Usage:** {usage}

## 4. Component Stylings

### Buttons
{buttons}

### Cards/Containers
{cards}

### Inputs/Forms
{inputs}

## 5. Layout Principles

{layout}

## 6. Design System Notes for Stitch Generation

When generating new screens, use these tokens:

- **Color Mode:** {colorMode}
- **Primary Color:** {customColor}
- **Font:** {font}
- **Roundness:** {roundness}
- **Saturation:** {saturation}

---

_Generated by stitch-mcp-cli on {date}_
`;

function describeRoundness(roundness: string): string {
  const descriptions: Record<string, string> = {
    ROUND_NONE: "Sharp, squared-off edges",
    ROUND_TWO: "Subtly rounded corners (2px)",
    ROUND_FOUR: "Gently rounded corners (4px)",
    ROUND_EIGHT: "Noticeably rounded corners (8px)",
    ROUND_SIXTEEN: "Prominently rounded corners (16px)",
    ROUND_FULL: "Pill-shaped (fully rounded)",
  };
  return descriptions[roundness] || roundness;
}

function describeColorMode(mode: string): string {
  const descriptions: Record<string, string> = {
    LIGHT: "Light mode with bright, airy feel",
    DARK: "Dark mode with deep, immersive feel",
    DYNAMIC: "Adapts based on system preference",
  };
  return descriptions[mode] || mode;
}

function generateDesignMd(metadata: StitchMetadata): string {
  const theme = metadata.designTheme || {
    colorMode: "LIGHT",
    font: "INTER",
    roundness: "ROUND_EIGHT",
    customColor: "#4F46E5",
    saturation: 1,
  };

  const atmosphere = describeColorMode(theme.colorMode);
  const roundnessDesc = describeRoundness(theme.roundness);

  const colors = [
    { name: "Primary", hex: theme.customColor || "#4F46E5", role: "Primary actions, key interactive elements" },
    { name: "Background", hex: theme.colorMode === "DARK" ? "#1F2937" : "#FFFFFF", role: "Page background" },
    { name: "Surface", hex: theme.colorMode === "DARK" ? "#374151" : "#F3F4F6", role: "Card backgrounds, elevated surfaces" },
    { name: "Text Primary", hex: theme.colorMode === "DARK" ? "#F9FAFB" : "#111827", role: "Main text content" },
    { name: "Text Secondary", hex: theme.colorMode === "DARK" ? "#9CA3AF" : "#6B7280", role: "Secondary text, labels" },
  ];

  const colorsTable = colors
    .map((c) => `| ${c.name} | ${c.hex} | ${c.role} |`)
    .join("\n");

  return DESIGN_MD_TEMPLATE
    .replace("{title}", metadata.title || "Untitled Project")
    .replace("{projectId}", metadata.projectId)
    .replace("{atmosphere}", atmosphere)
    .replace("{colors}", colorsTable)
    .replace("{font}", theme.font || "INTER")
    .replace("{weights}", "Regular (400), Medium (500), Bold (700)")
    .replace("{usage}", "Use bold for headings, regular for body text, medium for UI labels")
    .replace("{buttons}", `Shape: ${roundnessDesc}\nColors: Primary color with hover states`)
    .replace("{cards}", `Corner radius: ${roundnessDesc}\nBackground: Surface color with subtle shadow`)
    .replace("{inputs}", `Border radius: ${roundnessDesc}\nBackground: Slightly darker than page`)
    .replace("{layout}", "16px base spacing grid, 8px for tight spacing, 24px for sections")
    .replace("{colorMode}", theme.colorMode || "LIGHT")
    .replace("{customColor}", theme.customColor || "#4F46E5")
    .replace("{font}", theme.font || "INTER")
    .replace("{roundness}", roundnessDesc)
    .replace("{saturation}", String(theme.saturation || 1))
    .replace("{date}", new Date().toISOString().split("T")[0]);
}

export async function designMd(options: { projectId?: string; output?: string; sync?: boolean }) {
  const outputPath = options.output || "DESIGN.md";

  try {
    const { stitch } = getStitchClient();

    let projectId = options.projectId;
    let project;

    if (projectId) {
      project = stitch.project(projectId);
    } else {
      const metadata = readMetadata();
      if (metadata?.projectId) {
        projectId = metadata.projectId;
        project = stitch.project(projectId);
      } else {
        const projects = await stitch.projects();
        if (projects.length === 0) {
          console.error("No projects found. Provide a project ID or create one first.");
          process.exit(1);
        }
        project = projects[0];
        projectId = project.id;
      }
    }

    console.log(`Fetching project details for: ${projectId}`);

    const projectDetails = await stitch.callTool("get_project", { name: `projects/${projectId}` }) as any;

    const metadata: StitchMetadata = {
      projectId: projectId!,
      title: projectDetails?.title || "Untitled",
      deviceType: projectDetails?.deviceType || "MOBILE",
      designTheme: projectDetails?.designTheme as DesignTheme || undefined,
      screens: {},
    };

    const screens = await project.screens();
    console.log(`Project has ${screens.length} screens`);

    if (!fs.existsSync(".stitch")) {
      fs.mkdirSync(".stitch", { recursive: true });
    }

    writeMetadata(metadata);

    const designMd = generateDesignMd(metadata);
    fs.writeFileSync(outputPath, designMd);

    console.log(`OK Design system saved to ${outputPath}`);
    console.log(`OK Metadata saved to .stitch/metadata.json`);

    if (options.sync) {
      console.log("\nSyncing all screens to .stitch/designs/...");
      const designsDir = path.join(".stitch", "designs");
      if (!fs.existsSync(designsDir)) {
        fs.mkdirSync(designsDir, { recursive: true });
      }

      for (const screen of screens) {
        try {
          const html = await screen.getHtml();
          const screenFile = path.join(designsDir, `${screen.screenId.slice(0, 8)}.html`);
          fs.writeFileSync(screenFile, html);
          console.log(`  OK ${screen.screenId.slice(0, 8)}`);
        } catch (error) {
          console.error(`  X ${screen.screenId}: ${error instanceof Error ? error.message : error}`);
        }
      }
      console.log(`\nOK ${screens.length} screens synced to ${designsDir}`);
    }
  } catch (error) {
    console.error("Error generating design system:", error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
